# permissions for end users to view loggingsetups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loggingsetup-viewer-role
rules:
- apiGroups:
  - logging.world-direct.at
  resources:
  - loggingsetups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logging.world-direct.at
  resources:
  - loggingsetups/status
  verbs:
  - get
